# fly.toml app configuration file generated for tineri-chioselia-tabara on 2026-05-19T11:56:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tineri-chioselia-tabara'
primary_region = 'fra'

[build]

[env]
  DB_PATH = '/data/tabara.db'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
